export const FETCH_SETTINGS_SUCCESS = 'FETCH_SETTINGS_SUCCESS';
export const FETCH_SETTINGS_FAIL = 'FETCH_SETTINGS_FAIL';

export const FETCH_WINNERS_START = 'FETCH_WINNERS_START';
export const FETCH_WINNERS_SUCCESS = 'FETCH_WINNERS_SUCCESS';
export const FETCH_WINNERS_FAIL = 'FETCH_WINNERS_FAIL';

export const GAME_STARTED = 'GAME_STARTED';

export const POST_WINNER_START = 'POST_WINNER_START';
export const POST_WINNER_SUCCESS = 'POST_WINNER_SUCCESS';
export const POST_WINNER_FAIL = 'POST_WINNER_FAIL';
